#!/usr/bin/env python3
"""
Tests for the per-watch pages, the structured data, the sitemap and the feed.

These pages are the site's whole search surface and nobody reviews them — there
are 246 and they are regenerated by a bot. So what gets pinned here is not
rendering. It is the four things that would be WRONG IN PUBLIC and invisible to
us:

  1. An InStock claim to a crawler for a page nobody read. Structured data is
     machine-consumed and cannot carry a caveat, so the honesty rule that governs
     the register's prose has to be enforced harder here, not softer.
  2. A second outbound link. One outbound click is Lowell's rule and 246
     generated pages are exactly where it would erode without anyone noticing.
  3. A page for an entry the register does not show — retracted or out of scope.
     data.json keeps those deliberately; publishing them would put a claim we
     have withdrawn back in front of a search engine.
  4. A canonical, sitemap entry or feed link that points somewhere that is not
     that page. Wrong canonicals are the classic way a site de-indexes itself.

Run:  python3 test/pages_test.py
"""

from __future__ import annotations

import glob
import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import pages as P  # noqa: E402

PASS = FAIL = 0


def check(label: str, got, want) -> None:
    global PASS, FAIL
    if got == want:
        PASS += 1
        print(f"  ok    {label}")
    else:
        FAIL += 1
        print(f"  FAIL  {label}: got {got!r}, expected {want!r}")


def section(title: str) -> None:
    print(f"\n{title}\n" + "-" * len(title))


payload = json.loads((ROOT / "data.json").read_text(encoding="utf-8"))
watches = payload["watches"]
NOT_LE = [re.compile(r"not formally limited", re.I), re.compile(r"^capped", re.I),
          re.compile(r"annually", re.I)]
shown = [w for w in watches
         if not w.get("retracted")
         and not any(rx.search(str(w.get("edition", "")).strip()) for rx in NOT_LE)]
held = [w for w in watches if w not in shown]

files = sorted(glob.glob(str(ROOT / P.PAGES_DIR / "*.html")))
by_path = {}
for f in files:
    by_path[os.path.relpath(f, ROOT).replace(os.sep, "/")] = Path(f).read_text(encoding="utf-8")
# A retired path is a redirect stub, not a page. Split them out before counting.
redirects = {k: v for k, v in by_path.items() if 'http-equiv="refresh"' in v}
pages_out = {k: v for k, v in by_path.items() if k not in redirects}

# ---------------------------------------------------------------------------
section("One page per rendered entry — and none for anything held back")

check("every rendered entry has a page",
      sorted(pages_out) == sorted(P.path_for(w) for w in shown), True)
check("no page for a retracted or out-of-scope entry",
      [w["id"] for w in held if P.path_for(w) in pages_out], [])
check("paths are unique", len(set(pages_out)), len(pages_out))
check("retired paths are noindex redirects, never 404s",
      all('content="noindex,follow"' in v for v in redirects.values()), True)

manifest = json.loads((ROOT / P.MANIFEST).read_text(encoding="utf-8"))
check("the manifest records every live page", sorted(manifest.values()), sorted(pages_out))

# ---------------------------------------------------------------------------
section("Structured data is a claim to a machine, so it has to be true")

lds = {}
for rel, s in pages_out.items():
    m = re.search(r'<script type="application/ld\+json">(.*?)</script>', s, re.S)
    lds[rel] = json.loads(m.group(1)) if m else None

check("every page carries a Product node", sum(1 for v in lds.values() if v), len(pages_out))
check("all of them are @type Product",
      {v["@type"] for v in lds.values()}, {"Product"})
check("every one has a name, a brand, a description and an offer",
      [r for r, v in lds.items()
       if not (v.get("name") and v.get("brand") and v.get("description") and v.get("offers"))], [])

by_id = {w["id"]: w for w in shown}
instock = [r for r, v in lds.items() if v["offers"]["availability"].endswith("InStock")]


def entry_for(rel):
    return by_id[rel.rsplit("-", 1)[1].removesuffix(".html")]


check("InStock is emitted ONLY where a purchase page was read and classified",
      [r for r in instock if entry_for(r).get("buyKind") != "product"], [])
check("InStock is emitted ONLY for the buy-online tier",
      [r for r in instock if entry_for(r)["tier"] != "Buy online now"], [])
check("a sold-out entry says SoldOut",
      {lds[P.path_for(w)]["offers"]["availability"].rsplit("/", 1)[1]
       for w in shown if w["tier"] == "Gone"}, {"SoldOut"})
check("no price is invented where the register has none",
      [r for r, v in lds.items()
       if "price" in v["offers"] and entry_for(r).get("priceNum") is None], [])
check("every emitted price matches the register exactly",
      [r for r, v in lds.items()
       if "price" in v["offers"] and v["offers"]["price"] != entry_for(r)["priceNum"]], [])
check("a price always carries its currency",
      [r for r, v in lds.items() if ("price" in v["offers"]) != ("priceCurrency" in v["offers"])], [])
check("the register's own tier rule and the availability map cannot disagree",
      P.availability({"tier": "Buy online now", "buyKind": "listing"}),
      "https://schema.org/LimitedAvailability")

# ---------------------------------------------------------------------------
section("One outbound click")

EXTERNAL = re.compile(r'<a[^>]+href="(https?://[^"]+)"')
offenders = []
for rel, s in pages_out.items():
    links = [u for u in EXTERNAL.findall(s) if "watchdropindex.com" not in u]
    w = entry_for(rel)
    if links != [w["buy"]]:
        offenders.append((rel, links))
check("the buy link is the only link that leaves the site", offenders[:3], [])
check("the source is credited without being a link",
      all("Reported by" in s for s in pages_out.values()), True)
check("every page links back into the register",
      [r for r, s in pages_out.items() if f'href="{P.CANON}/#{entry_for(r)["id"]}"' not in s], [])
check("the register does not link out to them — they are landing targets",
      "/w/" in (ROOT / "index.html").read_text(encoding="utf-8").split("<body")[1]
      .split('type="application/ld+json"')[0], False)

# ---------------------------------------------------------------------------
section("Canonicals, sitemap and feed point where they say")

bad_canon = [rel for rel, s in pages_out.items()
             if f'<link rel="canonical" href="{P.CANON}/{rel}">' not in s]
check("each page is canonical to itself", bad_canon, [])
check("each page declares exactly one canonical",
      {len(re.findall(r'rel="canonical"', s)) for s in pages_out.values()}, {1})

sm = (ROOT / "sitemap.xml").read_text(encoding="utf-8")
locs = re.findall(r"<loc>(.*?)</loc>", sm)
check("the sitemap lists the index and every page", len(locs), len(pages_out) + 1)
check("no duplicate locs", len(set(locs)), len(locs))
check("every loc resolves to a file that exists",
      [u for u in locs if u != f"{P.CANON}/" and u.removeprefix(P.CANON + "/") not in pages_out], [])
check("lastmod tracks meta.updated",
      set(re.findall(r"<lastmod>(.*?)</lastmod>", sm)), {str(payload["meta"]["updated"])})
check("a retired path is never advertised in the sitemap",
      [u for u in locs if u.removeprefix(P.CANON + "/") in redirects], [])

fx = (ROOT / "feed.xml").read_text(encoding="utf-8")
fj = json.loads((ROOT / "feed.json").read_text(encoding="utf-8"))
check("the feed is capped", len(fj["items"]) <= P.FEED_MAX, True)
check("both feeds carry the same items", len(re.findall(r"<item>", fx)), len(fj["items"]))
check("every feed link resolves to a page",
      [i["url"] for i in fj["items"] if i["url"].removeprefix(P.CANON + "/") not in pages_out], [])
check("feed guids are unique", len({i["id"] for i in fj["items"]}), len(fj["items"]))
check("newest first",
      [i["date_published"] for i in fj["items"]],
      sorted((i["date_published"] for i in fj["items"]), reverse=True))
check("the index advertises the feed",
      'rel="alternate" type="application/rss+xml"' in (ROOT / "index.html").read_text(encoding="utf-8"), True)

# ---------------------------------------------------------------------------
section("The page a person actually lands on")

check("the title carries the words people search for",
      all(re.search(r"<title>.*price, edition size and where to buy", s) for s in pages_out.values()), True)
check("verification is stated on every page, including where there is none",
      [r for r, s in pages_out.items()
       if not re.search(r"Verified|Buy link checked|Not yet verified", s)], [])
check("an unverified entry says so rather than implying a check",
      "Not yet verified" in pages_out[P.path_for(next(w for w in shown if not w.get("verified") and not w.get("buyCheck")))],
      True)
check("the stylesheet is shared, not inlined 246 times",
      (ROOT / P.PAGES_DIR / "page.css").exists() and
      all("<style>" not in s for s in pages_out.values()), True)
check("the takedown address is on every page",
      [r for r, s in pages_out.items() if "takedown@watchdropindex.com" not in s], [])

# ---------------------------------------------------------------------------
section("Slugs and URL stability")

check("slugs are lowercase, ascii and hyphenated",
      [r for r in pages_out if not re.fullmatch(r"w/[a-z0-9-]+\.html", r)], [])
check("a collab keeps both names in the URL",
      P.slug("Seiko × SEGA chronograph"), "seiko-x-sega-chronograph")
check("accents are folded rather than dropped",
      P.slug("Grönefeld 1941 Rémontoire"), "gronefeld-1941-remontoire")
check("the id is what makes a path unique, not the slug",
      P.path_for({"brand": "A", "model": "B", "id": "abc123"}), "w/a-b-abc123.html")

print(f"\n{'ALL PASS' if not FAIL else 'FAILURES'} — {PASS} passed, {FAIL} failed\n")
sys.exit(1 if FAIL else 0)
