/**
 * Watch Drop Index — favourites.
 *
 * Two operations and no schema, which is the specification rather than a
 * shortcut: Lowell was explicit that he does not want a backend, and a star that
 * grows an account system stops being a star. If a future change to this file
 * needs a second table, that is the signal to push back, not to add one.
 *
 *   GET  /fav            → { "<id>": n, ... }   every non-zero count, one call
 *   POST /fav            → { id, device, on }   sets or clears this device's star
 *
 * WHY THE COUNT LIVES IN KV METADATA. A list() returns each key's metadata with
 * it, so the whole tally is one request. The obvious alternative — a single
 * aggregate blob — loses a star whenever two people click at once, and the other
 * — one get() per watch — is 246 round trips to render a page.
 *
 * WHAT THIS DELIBERATELY DOES NOT DO:
 *   · no accounts, no cookies, no IP logging. The device id is generated in the
 *     browser and means nothing to us beyond "one star per watch".
 *   · no zero is ever returned. A watch nobody has starred is ABSENT from the
 *     response, because absence and zero look identical to a reader and only one
 *     of them reads as rejection.
 *   · no write path that can invent a count: an increment requires a device that
 *     has not already starred that id, and the marker is what proves it.
 */

const ORIGINS = new Set([
  "https://www.watchdropindex.com",
  "https://watchdropindex.com",
]);

// The register's ids are 10 hex characters, generated by the refresh job. Anything
// else is not a watch and must not be able to create a key.
const ID = /^[a-f0-9]{10}$/;
const DEVICE = /^[a-zA-Z0-9_-]{8,64}$/;

function cors(origin) {
  const h = {
    "access-control-allow-methods": "GET,POST,OPTIONS",
    "access-control-allow-headers": "content-type",
    "access-control-max-age": "86400",
  };
  // Echoed only for origins we know. An unknown origin gets a working response
  // with no CORS header, which the browser then refuses — the correct outcome,
  // and one that does not require us to guess who is embedding us.
  if (ORIGINS.has(origin)) h["access-control-allow-origin"] = origin;
  return h;
}

const json = (body, origin, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json", ...cors(origin) },
  });

async function readAll(env) {
  const out = {};
  let cursor;
  do {
    const page = await env.FAVS.list({ prefix: "c:", cursor, limit: 1000 });
    for (const k of page.keys) {
      const n = k.metadata && k.metadata.n;
      if (n > 0) out[k.name.slice(2)] = n;   // never a zero
    }
    cursor = page.list_complete ? null : page.cursor;
  } while (cursor);
  return out;
}

async function setStar(env, id, device, on) {
  const marker = `d:${device}:${id}`;
  const already = await env.FAVS.get(marker);
  if (on === !!already) return null;         // idempotent: nothing to do

  const key = `c:${id}`;
  const cur = await env.FAVS.getWithMetadata(key);
  const n = Math.max(0, ((cur.metadata && cur.metadata.n) || 0) + (on ? 1 : -1));

  // The marker is written FIRST when starring and LAST when unstarring, so a
  // failure between the two writes can only ever under-count. A star that did
  // not register is a disappointment; one that registered twice is a lie about
  // how many people want the watch, and this register is sold on not lying.
  if (on) {
    await env.FAVS.put(marker, "1");
    await env.FAVS.put(key, "", { metadata: { n } });
  } else {
    await env.FAVS.put(key, "", { metadata: { n } });
    await env.FAVS.delete(marker);
  }
  return n;
}

export default {
  async fetch(request, env) {
    const origin = request.headers.get("origin") || "";
    const url = new URL(request.url);

    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors(origin) });
    if (url.pathname !== "/fav") return json({ error: "not found" }, origin, 404);

    if (request.method === "GET") {
      const counts = await readAll(env);
      return new Response(JSON.stringify(counts), {
        headers: {
          "content-type": "application/json",
          // Short and shared. The tally is interesting, not urgent, and a
          // register that survives being linked from Reddit matters more than
          // a count that is thirty seconds fresher.
          "cache-control": "public, max-age=30, s-maxage=30",
          ...cors(origin),
        },
      });
    }

    if (request.method === "POST") {
      if (!ORIGINS.has(origin)) return json({ error: "forbidden" }, origin, 403);
      let body;
      try {
        body = await request.json();
      } catch {
        return json({ error: "bad request" }, origin, 400);
      }
      const { id, device, on } = body || {};
      if (!ID.test(String(id || "")) || !DEVICE.test(String(device || "")))
        return json({ error: "bad request" }, origin, 400);

      const n = await setStar(env, id, device, on !== false);
      return json({ id, n }, origin);
    }

    return json({ error: "method not allowed" }, origin, 405);
  },
};
